---
retrieve_contracts_task:
  description: >
    Retrieve decrees, laws, orders articles or an other informations of the website www.bocs-primature.sn from the vector database using QdrantVectorSearchTool
    Focus on extracting the data needed for specific articles, decrees or laws that require analysis.
    You need to retrieve the relevant decrees or laws or orders from the vector database based on the query: {query}
  expected_output: A dataset containing all relevant articles, decrees or laws or orders with specific clauses
    extracted, ready for analysis.
  agent: data_retrieval_analysis_specialist
source_citer_task:
  description: Your goal is to retrieve the sources of answers for {query}
  expected_output: >
    A list of sources that contain the answers for {query}. 
    We will be using the sources identify where the answer came from.
    Sources are the sections, paragraphs, balise website or other identifiers that contain the answer.
  agent: source_citer_specialist

scrape_website_task:
  description: >
    Scrape content from the website  and answer the question: {query}.
  expected_output: A synthesized answer to the query, based on the content extracted from the website.
  agent: website_scraping_specialist

generate_report_task:
  description: Generate a report detailing results with sources using analytics
    of Task 2. Be sure to provide the specific clauses that were parsed, show which section, and identify which file it came from.
  expected_output: a comprehensive report that includes detailed conflict findings,
    similarities, differences and sources of the articles, laws, decrees, orders or website analyzed and make analisis in french.
  agent: report_generation_specialist
  output_file: report.md
